/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Ez4AsYuxQp0
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function PDFUpload() {
  return (
    <Card className="w-full max-w-xl">
      <CardHeader>
        <CardTitle>Upload PDF</CardTitle>
        <CardDescription>Add a PDF file and a description to share with your team.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="file">PDF File</Label>
          <Input id="file" type="file" accept=".pdf" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="description">Description</Label>
          <Textarea
            id="description"
            placeholder="Add a description for your PDF file..."
            rows={4}
            className="resize-none"
          />
        </div>
        <div className="border rounded-md overflow-hidden">
          {/* <iframe src="/placeholder.pdf" className="w-full h-[500px]" title="PDF Preview" /> */}
        </div>
      </CardContent>
      <CardFooter>
        <Button type="submit" className="ml-auto">
          Upload
        </Button>
      </CardFooter>
    </Card>
  )
}
